In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(np.argmax(a))

5

In [4]:
b=np.array([2,4,5,6,7])
print(np.argmin(b))

0

In [12]:
s=np.where(a>2)
s

(array([2, 3, 4, 5]),)

In [9]:
d=np.cumsum([1,2,3,5,6])
d

array([ 1,  3,  6, 11, 17])

In [11]:
r=np.random.randint(1,20,10)
r

array([13,  7, 16,  4,  7,  8,  6,  7, 17,  9,  1, 16,  2, 11,  5, 19, 16,
        9, 15, 11])

In [16]:
a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,14])
print(np.corrcoef(a,b))

[[1.        0.9686196]
 [0.9686196 1.       ]]

In [18]:
a=np.array([1,2,3,4,5,6])
print(a[:3])

[1 2 3]

In [19]:
print(a[3:])

[4 5 6]

In [22]:
print(a[1:6])

[2 3 4 5 6]

In [23]:
print(a[1:6:2])

[2 4 6]

In [26]:
print(a[::4])
print(a[-3:])

[1 5]
[4 5 6]

In [27]:
print(a[-2:])

[5 6]

In [28]:
arr=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,2]])
print(arr[0:1,1:3])

[[2 3]]

In [29]:
print(arr[:,1:2])

[[2]
 [4]
 [8]]

In [31]:
print(arr[:,::2])

[[1 3]
 [3 5]
 [7 9]]

In [32]:
import pandas as pd

In [33]:
c=pd.read_csv("StudentsPerformance.csv")
c

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [35]:
d={"name":["sudhan","ram","franklin"],
   
    "age":[20,19,26]}

In [38]:
c=pd.DataFrame(d)
c

       name  age
0    sudhan   20
1       ram   19
2  franklin   26

In [39]:
f=c.to_csv("friends.csv")

In [40]:
d=pd.read_csv("friends.csv")
d

   Unnamed: 0      name  age
0           0    sudhan   20
1           1       ram   19
2           2  franklin   26

In [41]:
print(d["age"],d["name"])

0    20
1    19
2    26
Name: age, dtype: int64 0      sudhan
1         ram
2    franklin
Name: name, dtype: object

In [45]:
print(d.loc[0:1,["name","age"]])

     name  age
0  sudhan   20
1     ram   19

In [47]:
print(d.loc[:,"name"])

0      sudhan
1         ram
2    franklin
Name: name, dtype: object

In [50]:
print(d.loc[:,"age"])

0    20
1    19
2    26
Name: age, dtype: int64